ARG NODE_VERSION=lts-slim

# Build and Run stage
FROM node:${NODE_VERSION}

WORKDIR /app

COPY  ./bin/npmentrypoint /entrypoint
RUN sed -i 's/\r$//g' /entrypoint
RUN chmod +x /entrypoint

ENTRYPOINT ["/entrypoint"]
