version: '3.9'

volumes:
  frello_psql: {}
  frello_poetry_cache: {}

services:
  app: &django
    build:
      context: .
      dockerfile: Dockerfile.django.dev
    image: frello
    container_name: frello_app
    restart: always
    depends_on:
      - postgres
      - mailhog
    volumes:
      - ${PWD}:/app
      - frello_poetry_cache:/root/.cache/pypoetry
    ports:
      - '8000:8000'
    command:
      - 'python'
      - 'manage.py'
      - 'runserver'
      - '0.0.0.0:8000'

  postgres:
    image: postgres:13
    container_name: frello_postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - frello_psql:/var/lib/postgresql/data:Z

  mailhog:
    image: mailhog/mailhog
    container_name: frello_mailhog
    ports:
      - 8025:8025 # web ui

  adminer:
    image: adminer
    container_name: frello_adminer
    restart: always
    ports:
      - 8080:8080
