# Generated by Django 4.0.4 on 2022-04-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frello', '0004_issue_description_issue_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', verbose_name='Project description'),
        ),
    ]
