name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE.txt
